### ISSUE TITLE
Marion ignores the storage backend and always tries saving documents to the file system

### ISSUE THREAD

**Issue by sampaccoud** [openfun/marion#84]
## Bug Report

**Expected behavior/code**
Documents should be persisted via the storage backend configured in the Django project running Marion.

**Actual Behavior**
We write files directly to the file system regardless of the storage backend:
https://github.com/openfun/marion/blob/5428dcac6306e9be1dba9d700109f3666debd60c/src/marion/marion/issuers/base.py#L367

**Steps to Reproduce**
1. Install Marion in a project where DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage' configured to connect to an S3 bucket,
2. Create a persisted document,
3. Notice that it wasn't created in the bucket but on the file system

**Environment**
- Marion version: v0.3.2
- Platform: Docker

**Possible Solution**
Get the generated file and save it using the active storage backend.

**Comment by jmaupetit** [comment]
In fact you can deal with persistence in your issuer, but you are right: we should default to the configured storage backend.
